
sources = files(
     'Worker.cpp'
    ,'DbusWorker.cpp'
    ,'ThreadWorker.cpp'
    ,'PicnicApp.cpp'
    ,'PicnicWindow.cpp'
    ,'PicnicView.cpp'
    ,'Pict.cpp'
    ,'Tile.cpp'
    ,'Layout.cpp'
    ,'DirNode.cpp'
    ,'ImageIconList.cpp'
    ,'FileSupport.cpp'
    ,'FileTree.cpp'
    ,'FileTreeView.cpp'
    ,'RectLayout.cpp'
    ,'RollLayout.cpp'
    ,'FileFinder.cpp'
    ,'CubeLayout.cpp'
    )

